stages:
  - build
  - pages

build:
  extends: .docker
  stage: build
  variables:
    PAGES_BUILD_DIR: "public"
    GITLAB_DOCKER_BUILD: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-build
    BUILD: ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ci:iid-${CI_PIPELINE_IID}
  script:
    - dind-run "${GITLAB_DOCKER_BUILD}" --cache-from master build .
    - dind-run "${BUILD}" Rscript -e "rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')"
  artifacts:
    paths:
      - public

pages:
  extends: .docker
  stage: pages
  script:
    - "# Nothing to do here, just passing along artifacts"
  artifacts:
    paths:
      - public
  environment:
    name: "weinbergerlab.gitlab.io/git-going"
    url: "http://weinbergerlab.gitlab.io/git-going"
  only:
    - master
    - gitlab-ci

.docker:
  tags:
    - docker
  image: ${CI_REGISTRY}/ci-utilities/ci-commands/dind-ci
  services:
    - docker:19.03.1-dind