---
title: "Getting started with Git in RStudio"
author: "Ben Artin, ben@artins.org"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
---

# Setting up

In order to follow these tutorials, you will need the following tools:

## GitHub Desktop

If you don't already have GitHub Desktop installed, you can [download the installer from the GitHub website](https://desktop.github.com).

## Git command line tools

You can install Git command line tools from GitHub Desktop.

On a Mac, open GitHub Desktop and choose GitHub Desktop > Install Command Line Tool from the menu, then enter your Mac password.

On a Windows PC TBD.

## R

If you don't already have R installed, you can [download the installer from the R website](https://cloud.r-project.org). 

If you do have R installed, check that your R version is 3.5 or higher. To check your version of R, type this at your R prompt:

```
> getRversion()
[1] ‘3.6.0’
```

## RStudio

If you don't already have RStudio installed, you can [download the installer from the R website](https://rstudio.com/products/rstudio/download/#download).

If you do have RStudio installed, check that your RStudio version is 1.2 or higher. To check your version of RStudio, type this at your R prompt:

```
> RStudio.Version()$version
[1] ‘1.2.1335’
```

You'll also need to make sure that your RStudio is configured correctly to talk to your Git command line tools. In RStudio, choose Tools > Global Options from the menu, then look in the Git/SVN section. Make sure that "Enable version control interface for RStudio projects" is checked and that "Git executable" is set to "/usr/local/bin/git". Click "OK". 

## Atom

If you don't already have Atom installed, you can [download it from the Atom website](https://atom.io).

If you do have Atom installed, make sure it's version 1.40 or higher — open it and check About Atom in the menu. 
